name: noor_app
description: "NoorWeb - Your complete Islamic companion app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Networking
  dio: ^5.7.0

  # Storage
  shared_preferences: ^2.3.3

  # Location & Compass
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_compass: ^0.8.0

  # Animations
  flutter_animate: ^4.5.0

  # Fonts & UI
  google_fonts: ^6.2.1

  # Date / Hijri
  intl: ^0.19.0
  hijri: ^3.0.0

  # Icons
  font_awesome_flutter: ^10.7.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
